Refactoring out the duplication

diff --git a/schmokin b/schmokin
--- a/schmokin
+++ b/schmokin
@@ -1,92 +1,74 @@
 #! /bin/bash
-VERSION=VERSION_HERE
-#   while [ -n "$1" ]; do
-#       case "$1" in
-#       -v )
-#           echo "version $VERSION"
-#           exit 0
-#           ;;
-#       esac
-#       shift
-#   done
-
-export RED='\033[0;31m' export NC='\033[0m' # No Color
-export GREEN='\033[0;32m'
-
-CURL_HTTP_SED="s/^> ([A-Z]{3,6}) ([a-zA-Z0-9/\.\_\~\:\/\?\#\!\$\&\(\)\*\+\,\\\;]+) HTTP\/1.1/\1,\2/p"
-
-width=75
-data=""
 
 if [[ -p /dev/stdin ]]
 then
-    data=$(cat /dev/stdin)
+    export DATA=$(cat /dev/stdin)
 fi
 
-method=$(echo "$data" | sed -rn "$CURL_HTTP_SED"  | cut -d, -f1)
-path=$(echo "$data" | sed -rn "$CURL_HTTP_SED" | cut -d, -f2)
-
-
-fail=0
-
-printf '%s %s\n' $method $path
-printf '%0.1s' "-"{1..85}
-printf '\n'
-
-jqexpr=''
-jqvalue=''
-
-R=""
-
-pass(){
-    printf "%-${width}s [${GREEN}%s${NC}]\n" "$1" "${2:-PASS}"
-}
-
-fail(){
-    printf "%-${width}s [${RED}%s${NC}]\n" "$1" "${2:-FAIL}"
-    fail=1
-}
-
-msg=""
+VERSION=VERSION_HERE #Reaplced at build time
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+GREEN='\033[0;32m'
+BLUE='\033[0;34m'
+CURL_HTTP_SED="s/^> ([A-Z]{3,6}) ([a-zA-Z0-9/\.\_\~\:\/\?\#\!\$\&\(\)\*\+\,\\\;]+) HTTP\/1.1/\1,\2/p"
+WIDTH=75
+FAILED=0
+HTTP_METHOD=$(echo "$DATA" | sed -rn "$CURL_HTTP_SED"  | cut -d, -f1)
+HTTP_PATH=$(echo "$DATA" | sed -rn "$CURL_HTTP_SED" | cut -d, -f2)
 RESULT=""
+
+HEADING(){
+    printf "${BLUE}%s %s${NC}\n" $1
+    printf '%0.1s' "-"{1..85}
+    printf '\n'
+}
+
+PASS(){
+    printf "%-${WIDTH}s [${GREEN}%s${NC}]\n" "$1" "${2:-PASS}"
+}
+
+FAIL(){
+    printf "%-${WIDTH}s [${RED}%s${NC}]\n" "$1" "${2:-FAIL}"
+    FAILED=1
+}
+
+HEADING "$HTTP_METHOD $HTTP_PATH"
+
 
 while [ -n "$1" ]; do
     case "$1" in
     --status-code|-s )
-            actual=$(echo "$data" | sed -rn 's/.*HTTP\/1.[0-9].*([0-9]{3}).*/\1/p' | sed 's/\r//g')
+            actual=$(echo "$DATA" | sed -rn 's/.*HTTP\/1.[0-9].*([0-9]{3}).*/\1/p' | sed 's/\r//g')
             msg=$(printf "expected status code = %s actual %s" $2 $actual)
-            if echo "$data" | grep -q "HTTP/1.[0-9] $2";
+            if echo "$DATA" | grep -q "HTTP/1.[0-9] $2";
             then
-              pass "${msg}" "PASS"
+              PASS "${msg}" "PASS"
             else 
-              fail "$msg" "FAIL"
+              FAIL "$msg" "FAIL"
             fi
-            MODE="$1 $2"
             shift
             ;;
     --jq-expr)
         msg=$2
-        JSON=$(echo "$data" | tail -n -1) 
+        JSON=$(echo "$DATA" | tail -n -1) 
         RESULT=$(echo $JSON | jq "$2" | sed 's/\"//g')
        ;;
     --eq)
         msg="expected ${msg:0:60} = $2 actual $RESULT"
         if [ "$RESULT" = "$2" ];
         then
-         printf "%-${width}s [${GREEN}%s${NC}]\n" "$msg" "PASS"
+         PASS "$msg" "PASS"
         else
-         fail=1
-         printf "%-${width}s [${RED}%s${NC}]\n" "$msg" "FAIL"
+         FAIL "$msg" "FAIL"
         fi
        ;;
     --gt)
         msg="expected ${msg:0:60} > $2 actual $RESULT"
         if [ "$RESULT" -gt "$2" ];
         then
-         printf "%-${width}s [${GREEN}%s${NC}]\n" "$msg" "PASS"
+         PASS "$msg" "PASS"
         else
-         fail=1
-         printf "%-${width}s [${RED}%s${NC}]\n" "$msg" "FAIL"
+         FAIL "$msg" "FAIL"
         fi
        ;;
     -v )
@@ -99,12 +81,12 @@ done
 
 printf '%0.1s' "-"{1..85}
 printf '\n'
-if [ "$fail" = "1" ];
+if [ "$FAILED" = "1" ];
 then
-    printf "%-${width}s [${RED}%s${NC}]\n\n" "RESULT" "FAILURE"
-    exit $fail
+    PASS "RESULT" "FAILURE"
+    exit $FAILED
 else
-    printf "%-${width}s [${GREEN}%s${NC}]\n\n" "RESULT" "SUCCESS"
+    FAIL "RESULT" "SUCCESS"
     exit 0
 fi
 
