checkpoint

diff --git a/schmokin b/schmokin
--- a/schmokin
+++ b/schmokin
@@ -15,9 +15,11 @@ BLUE='\033[0;34m'
 CURL_HTTP_SED="s/^> ([A-Z]{3,6}) (.*) HTTP\/1.1/\1,\2/p"
 WIDTH=75
 FAILED=0
+EXTRA_PARAMS=0
 HTTP_METHOD=$(echo "$DATA" | sed -rn "$CURL_HTTP_SED"  | cut -d, -f1)
 HTTP_PATH=$(echo "$DATA" | sed -rn "$CURL_HTTP_SED" | cut -d, -f2)
 RESULT=""
+CURL_ARGS=()
 
 HEADING(){
     printf "${BLUE}%s %s${NC}\n" "$@"
@@ -36,9 +38,45 @@ FAIL(){
 
 HEADING "$HTTP_METHOD" "$HTTP_PATH"
 
+URL=$1
+export URL
+shift
+
+# Loop over the variables to get any args after the --
+whitespace="[[:space:]]"
+for arg in "$@";
+do
+    case "$arg" in
+        "--")
+            EXTRA_PARAMS=1
+            ;;
+        *)
+            if [ "$EXTRA_PARAMS" -eq 1 ];
+            then
+                if [[ $arg =~ $whitespace ]]
+                then
+                    CURL_ARGS+=(\"$arg\")
+                else
+                    CURL_ARGS+=($arg)
+                fi
+            fi
+            ;;
+    esac
+done
+
+CURL_ARGS+=("-v")
+CURL_ARGS+=("-s")
+CURL_ARGS+=("2>&1")
+
+
+echo "$CURL_ARGS"
+
+exit 1
+
 while [ -n "$1" ]; do
     case "$1" in
     --status-code|-s )
+            ARGS+=("-s,$2")
             actual=$(echo "$DATA" | sed -rn 's/.*HTTP\/1.[0-9].*([0-9]{3}).*/\1/p' | sed 's/\r//g')
             msg=$(printf "expected status code = %s actual %s" "$2" "$actual")
             if echo "$DATA" | grep -q "HTTP/1.[0-9] $2";
@@ -132,12 +170,14 @@ while [ -n "$1" ]; do
         exit 0
         ;;
     * )
-        FAIL "Unkonwn arg [$1]" "ERROR"
+		echo "invalid argument $1"
         exit 1
         ;;
     esac
     shift
 done
+
+echo "$CURL_ARGS"
 
 printf '%0.1s' "-"{1..85}
 printf '\n'
